# permissions for end users to view objectstoreclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: objectstoreclaim-viewer-role
rules:
- apiGroups:
  - objectstore.claims.atlas.infoblox.com.atlas.infoblox.com
  resources:
  - objectstoreclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - objectstore.claims.atlas.infoblox.com.atlas.infoblox.com
  resources:
  - objectstoreclaims/status
  verbs:
  - get
