---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - objectstore.claims.atlas.infoblox.com.atlas.infoblox.com
  resources:
  - objectstoreclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectstore.claims.atlas.infoblox.com.atlas.infoblox.com
  resources:
  - objectstoreclaims/finalizers
  verbs:
  - update
- apiGroups:
  - objectstore.claims.atlas.infoblox.com.atlas.infoblox.com
  resources:
  - objectstoreclaims/status
  verbs:
  - get
  - patch
  - update
