name: Build and push :main image

on:
  push:
    branches:
      - main

# When Slack webhook is enabled
#env:
#  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to GHCR
        env:
          IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
        run: |
          make buildx
# When Slack webhook is enabled
#      - uses: act10ns/slack@v1
#        with:
#          status: ${{ job.status }}
#          steps: ${{ toJson(steps) }}
#          channel: '#db-controller'
#        if: failure()